services:
  - type: web
    name: keyswitchwiki
    env: java
    plan: free
    buildCommand: bash mvnw clean install -DskipTests
    startCommand: java -jar target/keyswitchwiki-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DATABASE_URL
        fromDatabase:
          name: keyswitchwiki-db
          property: connectionString
      - key: IMAGE_UPLOAD_DIR
        value: /tmp/keyswitch-images

databases:
  - name: keyswitchwiki-db
    engine: postgres
    version: 15
    plan: free

